import Head from "next/head";
import { Container } from "react-bootstrap";
import styles from '../../styles/PageLayout.module.scss';
import { Navigation } from '../Navigation/Navigation';

type PageLayout = {
    title: string;
}

export const PageLayout = ({  title = 'Split', children}: React.PropsWithChildren<PageLayoutProps>): JSX.Element => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Navigation />
                <Container>
                    {children}
                </Container>
            </main>
        </>
    );
}